#!/bin/sh

set -eu

manual="
SYNOPSIS
    $0 [options] <command>

OPTIONS
    -r, --release
        Select Ubuntu release image. (bionic)
    -n, --name
        Change virtual machine name. (Provision)

COMMANDS
    update
        Download latest system image.
    up
        Create and boot new virtual machine.
    down
        Destroy current virtual machine.
    cidata
        Create cidata.iso from user-data and meta-data files.
"

name="Provision"
cidata="cidata.iso"
release="bionic"
image="$release-server-cloudimg-amd64.vmdk"
url="https://cloud-images.ubuntu.com/$release/current"

_help() {
    printf "$manual" >&2
    exit 0
}

_update() {
	curl -O $url/$image
}

_create() {
	VBoxManage createvm --name $name --ostype Ubuntu_64 --register
	VBoxManage modifyvm $name --memory 1024 --cpus 1 --boot1 disk \
        --uart1 0x3f8 4 --uartmode1 disconnected --nic1 nat \
        --natpf1 "guestssh1,tcp,,2222,,22" --natpf2 "guestssh2,tcp,,8222,,822"
	VBoxManage storagectl $name --name "IDE_0" --add ide
	VBoxManage storageattach $name --storagectl "IDE_0" --port 0 --device 0 --type hdd --medium $image
	VBoxManage storageattach $name --storagectl "IDE_0" --port 1 --device 0 --type dvddrive --medium $cidata
}

_down() {
	child=$(VBoxManage showmediuminfo disk $image | awk "/Child/ { print \$3 }")
	VBoxManage storageattach $name --storagectl "IDE_0" --port 0 --device 0 --medium none
	VBoxManage storageattach $name --storagectl "IDE_0" --port 1 --device 0 --medium none
	VBoxManage unregistervm $name --delete
	VBoxManage closemedium disk $child
	VBoxManage closemedium disk $image
	VBoxManage closemedium dvd $cidata
}

_up() {
    VBoxManage showvminfo $name >/dev/null 2>&1 || _create
	VBoxHeadless --startvm $name
}

_cidata() {
	mkisofs -o cidata.iso -volid cidata -joliet -rock user-data meta-data 
}

while test $# -gt 0; do
    argument="$1"
    shift
    case "$argument" in
        update)
            _update
            ;;
        up)
            _up
            ;;
        down)
            _down
            ;;
        cidata)
            _cidata
            ;;
        -n|--name)
            name="$1"
            shift
            ;;
        -r|--release)
            release="$1"
            shift
            ;;
        -h|--help|help|*)
            _help 
            ;;
    esac
done
