version: "3"

services:
  traefik:
    image: traefik:2.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
    networks:
      - traefik
    command:
      - --log.level=DEBUG
      - --api
      - --providers.docker
      - --providers.docker.watch
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --entrypoints.http.address=:80
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.$HOSTNAME`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.dummy-svc.loadbalancer.server.port=9999

networks:
  traefik:
    external: true
