version: "3"

services:
  web:
    image: containous/whoami
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami.$HOSTNAME`)
        - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  traefik:
    external: true
