version: "3"
services:
  web:
    image: containous/whoami
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.node-1`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  public:
    external: true
